version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 5.0
      #dotnet: latest - Latest resolve to 3.1, check this issue https://github.com/aws/aws-codebuild-docker-images/issues/414

  build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet build -c Release ./ClinicManagement/ClinicManagement.csproj
      
artifacts:
  files:
    - ./**/*
